Proxy handler
UCLA-CS130/Razzle-Dazzle pull request #29
Opened 2017-02-28 10:01 UTC by neosbob

Hello, this is TeamHello.

I am creating this pull request to keep track of all my changes for the proxy handler.

Progress:
    -Added files for proxy_handler.
    -updated config file and implemented Init Function for proxy_handler.

2017-02-28 16:46 UTC, RBarank commented
Hey just let us know when you're ready to merge.

2017-03-01 11:11 UTC, neosbob commented
There seems to be an issue where the server dumps core/ segmentation fault.
This happens when the browser is trying to request additional files from proxy server.

I suspect that this is because in connection.cc, the server doesn't know to use the proxy handler set with the path "/".  Currently, connection can't find any matching request handler to handle the subsequent requests.

The issue lies within the  second_slash search method.  The URI "/css/main.css" assumes the request_path is "/css", and doesn't check to see if any existing handler can handle the URI.

2017-03-01 11:19 UTC, abineetds commented
There is a bug with the uri_prefix being "/". That does dump core, but it shouldn't hamper anything unless you specify a handler with a uri_prefix of "/" in the config.

The problem you are talking about of the uri /css/main.css. The code will treat /css to be a uri prefix and try to search for a handler associated with that. You're right there is a bug that it ends up dumping core if the uri_prefix is not found in the map. That's a quick fix, to just search the map before trying to access it and set a bad request if not found.

2017-03-01 11:30 UTC, neosbob commented
Actually it does this after  saving a value to request_base: 
     RequestHandler::Status ret = pathMap_[request_base]->HandleRequest(*currentRequest, resp);

So if a request_base is not found, it does some weird stuff. Probably due to accessing nullptr.

Should you guys handle the fix? Or do I apply a fix? Not sure on this.

2017-03-01 11:39 UTC, abineetds commented
I know exactly what the problem is. It's only a small check that needs to
be done. I'm not on a machine right now, I can do it in the afternoon
tomorrow. It's only four or five lines of code, do its your choice. If I
fix it you're going to have to pull again.

On Mar 1, 2017 3:30 AM, "neosbob" <notifications@github.com> wrote:

> Actually it does this after saving a value to request_base:
> RequestHandler::Status ret = pathMap_[request_base]->HandleRequest(*currentRequest,
> resp);
>
> So if a request_base is not found, it does some weird stuff. Probably due
> to accessing nullptr.
>
> Should you guys handle the fix? Or do I apply a fix? Not sure on this.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/UCLA-CS130/Razzle-Dazzle/pull/29#issuecomment-283316730>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AKFo06yHUFOo8O_VUJLm1-Ux6Tx5e4zfks5rhVbHgaJpZM4MOMP5>
> .
>

2017-03-03 01:19 UTC, echen94 commented
There seems to be some issue in the Parse function of request.cc. 
There is an iterator error when we tried the Parse function for a request in our unit tests.
Also, the server crashes when we send another request during one session. It should not be a problem from the proxy server because it works fine with our own code. Let us know if you can figure out where the problem comes from. 

Here is the error message we got:
const Type& boost::token_iterator<TokenizerFunc, Iterator, Type>::dereference() const [with TokenizerFunc = boost::char_separator<char>; Iterator = __gnu_cxx::__normal_iterator<const char*, std::__cxx11::basic_string<char> >; Type = std::__cxx11::basic_string<char>]: Assertion `valid_' failed.

2017-03-03 01:28 UTC, RBarank commented
Ok we will look into it

2017-03-03 01:40 UTC, abineetds commented
Does the server crash have something to do with /favicon.ico?

2017-03-03 01:43 UTC, abineetds commented
What was the request you were sending when you got the iterator error?

2017-03-03 01:49 UTC, neosbob commented
So I open a session, enter localhost:3000/ in the browser. Everything works fine, the ucla webpage is displayed. 

Same session, enter localhost:3000/ in the browser. The iterator error occurs, and server crashes.

The favicon does cause the server to crash on localhost:3000/echo.

2017-03-03 02:56 UTC, abineetds commented
That's odd, let me check

2017-03-03 03:49 UTC, abineetds commented
I ran your most recent code, didn't give me an issue. The only thing I changed was I commented a cout statement in your proxy handler that was really populating the console. cout.write()

2017-03-03 03:58 UTC, neosbob commented
Try entering localhost:3000/ in the browser multiple times in one session.

2017-03-03 04:03 UTC, neosbob commented
The error pops up sporadically when certain conditions have been fulfilled.  I have also tested this on my team's server, and the above mentioned error did not appear.

2017-03-03 04:50 UTC, abineetds commented
That's weird, I think it might be an issue in which we cut off a request to
start sending fresh ones. I didn't see this problem but maybe the
multithreading will fix this.

On Mar 2, 2017 8:03 PM, "neosbob" <notifications@github.com> wrote:

> The error pops up sporadically when certain conditions have been
> fulfilled. I have also tested this on my team's server, and the above
> mentioned error did not appear.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/UCLA-CS130/Razzle-Dazzle/pull/29#issuecomment-283859765>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AKFo09Qzx8KBBQuV1C1XuknB0XxmmC7fks5rh5EtgaJpZM4MOMP5>
> .
>

2017-03-03 05:47 UTC, neosbob commented
So minus the above mentioned error, everything else works fine. Is it ok if we merge later?

2017-03-03 06:57 UTC, neosbob commented
Ready for merging.

2017-03-03 07:15 UTC, neosbob commented
Need an approved review.

2017-03-03 07:18 UTC, panjiyar commented on proxy_handler.cc
> +bool ProxyHandler::url_decode(const std::string& in, std::string& out)
is this function being used anywhere?

2017-03-03 07:22 UTC, panjiyar requested changes
Do you need the url_decode function in the handler. i don't see it being used

2017-03-03 07:25 UTC, neosbob commented
Oh ok, I'll remove it.

2017-03-03 07:40 UTC, neosbob commented
Removed the function.

2017-03-03 07:41 UTC, panjiyar approved these changes

2017-03-03 07:41 UTC, panjiyar commented
Will merge once check completes

2017-03-03 07:47 UTC, neosbob commented
Ok. Thanks!

2017-03-03 07:50 UTC, merged

2017-03-03 07:50 UTC, abineetds commented
Good job guys!